/**:
  ros__parameters:
    blind_spot:
      backward_attention_length: 100.0 # [m]
      ttc_start_margin: 2.0 # [s]
      ttc_end_margin: 1.0 # [s]
      collision_judge_debounce: 0.5 # [s]
      critical_stopline_margin: 1.0 # [m]
      enable_rtc: false # If set to true, the scene modules require approval from the rtc (request to cooperate) function. If set to false, the modules can be executed without requiring rtc approval
