units:
  - path: /autoware/sensing/autonomous_available
    type: and
    list:
      - { type: link, link: /autoware/sensing/emergency_stop }
      - { type: link, link: /autoware/sensing/pull_over }
      - { type: link, link: /autoware/sensing/comfortable_stop }

  - path: /autoware/sensing/pull_over_available
    type: and
    list:
      - { type: link, link: /autoware/sensing/emergency_stop }
      - { type: link, link: /autoware/sensing/comfortable_stop }

  - path: /autoware/sensing/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /autoware/sensing/emergency_stop }

  # ***************************************************

  - path: /autoware/sensing/emergency_stop
    type: and
    list:
      - { type: link, link: /autoware/sensing/imu/connection }
      - { type: link, link: /autoware/sensing/lidar/velodyne/connection }
      - { type: link, link: /autoware/sensing/lidar/velodyne/temperature }
      - { type: link, link: /autoware/sensing/lidar/velodyne/rpm }
      - { type: link, link: /autoware/sensing/camera/connection }

  - path: /autoware/sensing/pull_over
    type: and
    list:
      - { type: link, link: /autoware/sensing/lidar/velodyne/temperature }

  - path: /autoware/sensing/comfortable_stop
    type: and

  - path: /autoware/sensing/none
    type: and
    list:
      - { type: link, link: /autoware/sensing/imu/gyro_bias_validator }
      # - { type: link, link: /autoware/sensing/lidar/performance_monitoring/blockage }   ---->To be checked in v0.47.0
      - { type: link, link: /autoware/sensing/gnss/fix }
      - { type: link, link: /autoware/sensing/gnss/connection }

  # ***************************************************
  # Intermediate paths

  - path: /autoware/sensing/camera/connection
    type: and
    list:
      - { type: link, link: /autoware/sensing/camera/0/connection }
      - { type: link, link: /autoware/sensing/camera/1/connection }
      - { type: link, link: /autoware/sensing/camera/2/connection }
      - { type: link, link: /autoware/sensing/camera/3/connection }
      - { type: link, link: /autoware/sensing/camera/4/connection }
      - { type: link, link: /autoware/sensing/camera/5/connection }
      - { type: link, link: /autoware/sensing/camera/6/connection }

  # ***************************************************

  # Diagnostics paths
  - path: /autoware/sensing/imu/connection
    type: diag
    node: topic_state_monitor_imu
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/imu/gyro_bias_validator
    type: diag
    node: gyro_bias_validator
    name: gyro_bias_validator
    timeout: 1.0

  # ---->To be check in v0.47.0
  # - path: /autoware/sensing/lidar/performance_monitoring/blockage
  #   type: diag
  #   node: blockage
  #   name: blockage_validation
  #   timeout: 1.0

  - path: /autoware/sensing/lidar/velodyne/connection
    type: diag
    node: velodyne_monitor
    name: velodyne_connection
    timeout: 3.0

  - path: /autoware/sensing/lidar/velodyne/temperature
    type: diag
    node: velodyne_monitor
    name: velodyne_temperature
    timeout: 3.0

  - path: /autoware/sensing/lidar/velodyne/rpm
    type: diag
    node: velodyne_monitor
    name: velodyne_rpm
    timeout: 3.0

  - path: /autoware/sensing/gnss/connection
    type: diag
    node: ublox
    name: fix topic status
    timeout: 3.0

  - path: /autoware/sensing/gnss/fix
    type: diag
    node: ublox
    name: fix
    timeout: 3.0

  - path: /autoware/sensing/camera/0/connection
    type: diag
    node: topic_state_monitor_camera0
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/camera/1/connection
    type: diag
    node: topic_state_monitor_camera1
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/camera/2/connection
    type: diag
    node: topic_state_monitor_camera2
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/camera/3/connection
    type: diag
    node: topic_state_monitor_camera3
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/camera/4/connection
    type: diag
    node: topic_state_monitor_camera4
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/camera/5/connection
    type: diag
    node: topic_state_monitor_camera5
    name: sensing_topic_status
    timeout: 1.0

  - path: /autoware/sensing/camera/6/connection
    type: diag
    node: topic_state_monitor_camera6
    name: sensing_topic_status
    timeout: 1.0
