files:
  - { path: $(dirname)/autoware-main_gen2.yaml }

edits:
  - { type: remove, path: /hardware/cpu/002-usage }
  - { type: remove, path: /hardware/cpu/004-throttling }
  - { type: remove, path: /hardware/storage/001-temperature }
  - { type: remove, path: /hardware/storage/006-recovered }
  - { type: remove, path: /hardware/storage/007-load }
  - { type: remove, path: /hardware/memory/001-usage }
  - { type: remove, path: /hardware/network/003-crc }
  - { type: remove, path: /hardware/network/004-packet_reassembles }
  - { type: remove, path: /hardware/gpu/001-temperature }
  - { type: remove, path: /hardware/gpu/002-usage }
  - { type: remove, path: /hardware/gpu/003-memory }
  - { type: remove, path: /hardware/gpu/004-throttling }
  - { type: remove, path: /hardware/gpu/005-frequency }
  - { type: remove, path: /hardware/storage/002-usage }
  - { type: remove, path: /perception/001-topic_status/traffic_signals-error }
  - { type: remove, path: /sensing/lidar/concat/001-status }
  - { type: remove, path: /sensing/lidar/pandar/001-connection }
  - { type: remove, path: /sensing/lidar/pandar/002-temperature }
  - { type: remove, path: /sensing/lidar/pandar/003-ptp }
  - { type: remove, path: /sensing/camera/001-connection }
  - { type: remove, path: /sensing/lidar/pandar/002-temperature }
