units:
  - path: /foolproof/autonomous_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }
      - { type: link, link: /foolproof/pull_over }
      - { type: link, link: /foolproof/comfortable_stop }

  - path: /foolproof/pull_over_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }
      - { type: link, link: /foolproof/comfortable_stop }

  - path: /foolproof/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /foolproof/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /foolproof/emergency_stop
    type: and
    list:
      - { type: link, link: /foolproof/main/autoware_node_alive }

  - path: /foolproof/pull_over
    type: and

  - path: /foolproof/comfortable_stop
    type: and
    list:
      - { type: link, link: /foolproof/main/update_status_ota }
      - { type: link, link: /foolproof/main/update_status_map }
      - { type: link, link: /foolproof/main/update_status_unrecoverable }

  # *******************************************************************************
  # Set path, node to identify and name for each individual error.
  # *******************************************************************************
  # Heartbeat, watch other ECU is alive or not
  # - path: /foolproof/logging/heartbeat
  #   type: diag
  #   node: autoware_diagnostics_bridge_node_logging
  #   name: heartbeat
  #   timeout: 3.0
  #   latch: 0.0

  # letterbox_monitor
  - path: /foolproof/main/autoware_node_alive
    type: diag
    node: autoware_diagnostics_bridge_node_main # autoware_diagnostics_bridge_node_<host>
    name: main_autoware_node_alive # <host>_<mrm_name_suffix>
    timeout: 3.0
    latch: 0.0

  # update_status_checker
  - path: /foolproof/main/update_status_ota
    type: diag
    node: autoware_diagnostics_bridge_node_main # autoware_diagnostics_bridge_node_<host>
    name: main_update_status_checker_ota # <host>_<mrm_name_suffix>
    timeout: 3.0
    latch: 0.0

  - path: /foolproof/main/update_status_map
    type: diag
    node: autoware_diagnostics_bridge_node_main # autoware_diagnostics_bridge_node_<host>
    name: main_update_status_checker_map # <host>_<mrm_name_suffix>
    timeout: 3.0
    latch: 0.0

  - path: /foolproof/main/update_status_unrecoverable
    type: diag
    node: autoware_diagnostics_bridge_node_main # autoware_diagnostics_bridge_node_<host>
    name: main_update_status_checker_unrecoverable # <host>_<mrm_name_suffix>
    timeout: 3.0
    latch: 0.0
