/**:
  ros__parameters:
    class_names: ["CAR", "TRUCK", "BUS", "BICYCLE", "PEDESTRIAN"]
    rename_car_to_truck_and_bus: true
    point_feature_size: 4
    max_voxel_size: 40000
    point_cloud_range: [-121.6, -76.8, -3.0, 121.6, 76.8, 5.0]
    voxel_size: [0.32, 0.32, 8.0]
    downsample_factor: 1
    encoder_in_feature_size: 9
    # post-process params
    circle_nms_dist_threshold: 0.3
    iou_nms_target_class_names: ["CAR", "TRUCK", "BUS"]
    iou_nms_search_distance_2d: 10.0
    iou_nms_threshold: 0.1
    yaw_norm_thresholds: [0.3, 0.3, 0.3, 0.3, 0.0]
    score_threshold: 0.35
    has_variance: false
    has_twist: false
    trt_precision: fp16
    densification_num_past_frames: 1
    densification_world_frame_id: map

    # weight files
    encoder_onnx_path: "$(var model_path)/pts_voxel_encoder_$(var model_name).onnx"
    encoder_engine_path: "$(var model_path)/pts_voxel_encoder_$(var model_name).engine"
    head_onnx_path: "$(var model_path)/pts_backbone_neck_head_$(var model_name).onnx"
    head_engine_path: "$(var model_path)/pts_backbone_neck_head_$(var model_name).engine"
