# Description:
#   required_diags:
#     <name>: {is_active: <is_active>, status: <status>}
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:

      # Debug example
      # "node_A: name_B": default

      # map
      "topic_state_monitor_pointcloud_map: map_topic_status": default

      # control
      # joy_controller_connection: default

      # sensing
      # sensing monitoring items published by dummy_diag_publisher are saved at
      # /src/autoware/aip_launcher/aip_xx1_launch/config/dummy_diag_publisher/sensor_kit.param.yaml

      # localization
      "topic_state_monitor_pose_twist_fusion_filter_pose: localization_topic_status": default
      "ndt_scan_matcher: scan_matching_status": default
      "localization: localization_error_monitor": default
      "localization: ekf_localizer": default

      # hardware
      "ntp_monitor: NTP Offset": default
      "cpu_monitor: CPU Temperature": default
      "cpu_monitor: CPU Usage": default
      "cpu_monitor: CPU Thermal Throttling": default
      "cpu_monitor: CPU Frequency": default
      "cpu_monitor: CPU Load Average": default
      "gpu_monitor: GPU Temperature": default
      "gpu_monitor: GPU Usage": default
      "gpu_monitor: GPU Memory Usage": default
      "gpu_monitor: GPU Thermal Throttling": default
      "gpu_monitor: GPU Frequency": default
      "mem_monitor: Memory Usage": default
      "net_monitor: Network Usage": default
      "net_monitor: Network Traffic": default
      "net_monitor: Network CRC Error": default
      "net_monitor: IP Packet Reassembles Failed": default
      "hdd_monitor: HDD Temperature": default
      "hdd_monitor: HDD RecoveredError": default
      "hdd_monitor: HDD ReadDataRate": default
      "hdd_monitor: HDD WriteDataRate": default
      "hdd_monitor: HDD ReadIOPS": default
      "hdd_monitor: HDD WriteIOPS": default
      "hdd_monitor: HDD Usage": default
      "hdd_monitor: HDD PowerOnHours": default
      "hdd_monitor: HDD TotalDataWritten": default
      "hdd_monitor: HDD Connection": default
      "process_monitor: High-mem Proc[0]": default
      "process_monitor: High-mem Proc[1]": default
      "process_monitor: High-mem Proc[2]": default
      "process_monitor: High-mem Proc[3]": default
      "process_monitor: High-mem Proc[4]": default
      "process_monitor: High-load Proc[0]": default
      "process_monitor: High-load Proc[1]": default
      "process_monitor: High-load Proc[2]": default
      "process_monitor: High-load Proc[3]": default
      "process_monitor: High-load Proc[4]": default
      "process_monitor: Tasks Summary": default
      "voltage_monitor: CMOS Battery Status": default

      # vehicle
      # vehicle_errors: default
      # pacmod_errors: default
      # pacmod_accel_brake_fault: default
      # accel_brake_map_calibrator: default
