# This workflow is intended for the use in the repositories created by forking tier4/autoware_launch.
name: sync-tier4-upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: Base branch in the forked repository to sync to
        required: true
        default: tier4/main
      sync_target_branch:
        description: Target branch in the upstream repository to sync from
        required: true
        default: tier4/main

jobs:
  sync-tier4-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run sync-branches
        uses: autowarefoundation/autoware-github-actions/sync-branches@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: ${{ github.event.inputs.base_branch}}
          sync-pr-branch: sync-to-${{ github.event.inputs.base_branch}}
          sync-target-repository: https://github.com/tier4/autoware_launch.git
          sync-target-branch: ${{ github.event.inputs.sync_target_branch}}
          pr-title: "chore: sync upstream"
          pr-labels: |
            bot
            sync-tier4-upstream
          auto-merge-method: merge
